### ISSUE TITLE
Project is not compiling

### ISSUE THREAD

**Issue by Tschis** [gerardszczepanski/RollerCoasterTycoon#2]
Lots of compilation problems when downloading master and importing it in Eclipse.

![image](https://user-images.githubusercontent.com/20662669/34685583-fc6a563e-f48f-11e7-9a28-91d61c47a13c.png)

This is after solving issue #1.

**Comment by gerardszczepanski** [comment]
Hi, you have to install Lombok plugin. 

Try to run maven install - project is compiled correctly. To compile project in IDE you should install Lombok plugin.

**Comment by gerardszczepanski** [comment]
I'll add it. Thanks :+1:
